
services:
  web:
    build: .
    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  
      - /app/static  # или путь к вашим статическим файлам
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=app.settings